auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listings/create", views.create_listing, name="create_listing"),
    path("listings/<int:listing_id>", views.listing, name="listing"),
    path("listings/<int:listing_id>/comments", views.Add_Comments, name="add_comment"),
    path("listing/close/<int:listing_id>", views.close_listing, name="close_listing"),
    path("watchlist/<int:listing_id>", views.Add_to_Watchlist, name="add_to_watchlist"),
    path("watchlist", views.watchlist, name="my_watchlist"),
    path("categories", views.categories, name="all_categories"),
    path("categories/<int:category_id>", views.category, name="category"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ModelForm
from django.conf import settings

class User(AbstractUser):
    pass

class Auction_Listing(models.Model):
    status = models.BooleanField(default=True)
    user = models.ForeignKey(User, blank=False, on_delete=models.CASCADE, related_name="auctioner")
    category = models.ForeignKey('Category', blank=False, on_delete=models.CASCADE, related_name="listing_category")
    listing_name = models.CharField(max_length=50, blank=False)
    image = models.URLField(max_length=200)
    start_bid = models.DecimalField(blank=False, max_digits=5, decimal_places=2)
    highest_bid = models.ForeignKey('Bid', default=None, blank=True,null=True, on_delete=models.SET_NULL, related_name="listing_highest_bid")
    description = models.TextField(blank=False)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.listing_name} in {self.category} with starting price at ${self.start_bid}"

class Bid(models.Model):
    user = models.ForeignKey(User,default=None, on_delete=models.CASCADE,related_name="bidder",editable=False)
    listing_reference = models.ForeignKey(Auction_Listing, on_delete=models.CASCADE, default=None, related_name="listing_bids")
    bidding = models.DecimalField(blank=False,max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.user} bids ${self.bidding} to {self.listing_reference}"

class Comment(models.Model):
    user = models.ForeignKey(User,default=None,on_delete=models.CASCADE, related_name="commentator")
    listing_reference = models.ForeignKey(Auction_Listing, on_delete=models.CASCADE, default="", related_name="listing_comments")
    comment = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.user} comments to {self.listing_reference}"

class Watchlist(models.Model):
    user = models.ForeignKey(User,default=None,on_delete=models.CASCADE, related_name="watchlist")
    listing_reference = models.ManyToManyField(Auction_Listing, default=None, related_name="listing_watchlist")

    def __str__(self):
        return f"{self.user} Watchlist"


class Category(models.Model):
    category_name = models.CharField(max_length=50, blank=False)
    listing_reference = models.ManyToManyField(Auction_Listing, default=None, related_name="category_listings")
    
    def __str__(self):
        return f"{self.category_name}"

class AuctionForm(ModelForm):
    class Meta:
        model = Auction_Listing
        fields = "__all__"
        exclude = ['user','highest_bid',]

class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ['bidding']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import User, AuctionForm, Auction_Listing, Category, Comment, Bid, Watchlist
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, "auctions/index.html",{
        "listings":Auction_Listing.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            try:
                Watchlist.objects.get(user=request.user)
            except Watchlist.DoesNotExist:
                watchlist = Watchlist.objects.create(user=request.user)
                watchlist.save()
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            watchlist = Watchlist.objects.create(user=request.user)
            user.save()
            watchlist.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url='auctions:login')
def create_listing(request):
    if request.method == "POST":
        listing_name = request.POST["listing_name"]
        category = Category.objects.get(pk=int(request.POST["category"]))
        image = request.POST["image"]
        start_bid = request.POST["start_bid"]
        description = request.POST["description"]
        Listing = Auction_Listing.objects.create(user=request.user, status=True, category=category, listing_name=listing_name, image=image, start_bid=start_bid, description=description,highest_bid=None)
        Listing.save()
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request,"auctions/create_listing.html",{
            "cat_objs":Category.objects.all()
        })

def listing(request,listing_id):
    auction_list = Auction_Listing.objects.get(id=listing_id)
    watchlist_option = False
    winner = False
    bid_option = False
    comment_option = None
    error_message = False

    # For Active Status and Winner
    if not auction_list.status:
        try:
            winner = Bid.objects.get(bidding=auction_list.highest_bid.bidding)
            winner = "This Listing has already been sold to "+str(winner.user.username)+" at $"+str(auction_list.highest_bid.bidding)
        except Bid.DoesNotExist:
            winner = "This Listing is not active yet."

    # For Watchlist option
    if request.user.is_authenticated and auction_list.status==True:
        bid_option = True
        try:
            # Checks WatchList
            watchlist = Watchlist.objects.get(user=request.user)
            watchlist = watchlist.listing_reference.get(pk=auction_list.id)
            watchlist_option = False
        except Auction_Listing.DoesNotExist:
            watchlist_option = True
    
    # For Bidding option
    if request.method == "POST":
        price = int(request.POST["price"])
        if price > auction_list.start_bid and (auction_list.highest_bid == None or price > auction_list.highest_bid.bidding):
            try:                
                bidder = Bid.objects.get(user=request.user,listing_reference=auction_list)
                bidder.bidding = price
                bidder.save()
            except Bid.DoesNotExist:
                bidder = Bid.objects.create(user=request.user,listing_reference=auction_list, bidding=price)
            
            auction_list.highest_bid = bidder
            auction_list.save()
            return HttpResponseRedirect(reverse("auctions:listing", args=(listing_id,)))
        else:
            error_message = "Please enter amount higher than current highest bid."
        
    # For Listing Comments
    if request.user.is_authenticated and auction_list.status==True:
        try:
            comment_option = Comment.objects.filter(listing_reference=auction_list)
        except Comment.DoesNotExist:
            pass

    return render(request, "auctions/listing.html",{
        "listing":auction_list,
        "watchlist":watchlist_option,
        "list_status":auction_list.status,
        "winner":winner,
        "bid_option":bid_option,
        "comments":comment_option,
        "error_message":error_message,
    })

@login_required(login_url='auctions:login')
def Add_to_Watchlist(request,listing_id):
    auction_list = Auction_Listing.objects.get(id=listing_id)
    if request.user.is_authenticated and auction_list.status==True:
        try:
            watchlist = Watchlist.objects.get(user=request.user)
            watchlist.listing_reference.get(pk=auction_list.id)
            # If Listing_reference already exist(means user has clicked un-watch), so Delete WatchList
            watchlist.listing_reference.remove(auction_list)
        except Auction_Listing.DoesNotExist:
            # Add just listing_reference
            watchlist.listing_reference.add(auction_list)

    return HttpResponseRedirect(reverse("auctions:listing",args=(listing_id,)))

def Add_Comments(request,listing_id):
    if request.method == "POST":
        auction_list = Auction_Listing.objects.get(id=listing_id)
        comment = request.POST["comment"]
        Comment.objects.create(user=request.user, listing_reference=auction_list, comment=comment)

    return HttpResponseRedirect(reverse("auctions:listing",args=(listing_id,)))

def watchlist(request):
    all_listings = None
    try:
        my_watchlists = Watchlist.objects.get(user=request.user)
        all_listings = my_watchlists.listing_reference.all()
    except Watchlist.DoesNotExist:
        pass
    except Auction_Listing.DoesNotExist:
        pass
    return render(request, "auctions/watchlist.html",{
        "watchlists":all_listings
    })

def categories(request):
    return render(request, "auctions/categories.html",{
        "categories":Category.objects.all()
    })

def category(request,category_id):
    try:
        category = Category.objects.get(pk=category_id)
        auction_list = Auction_Listing.objects.get(category=category)
    except Category.DoesNotExist:
        category = "No Categories Yet"
    except Auction_Listing.DoesNotExist:
        auction_list = "No Listing Yet"
    return render(request, "auctions/category.html",{
        "category":category,
        "auction_list":auction_list
    })

def close_listing(request,listing_id):
    auction_list = Auction_Listing.objects.get(pk=listing_id)
    auction_list.status = not (auction_list.status)
    auction_list.save()
    return HttpResponseRedirect(reverse("auctions:listing",args=(listing_id,)))

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}

{% block body %}
    <h3>All Categories:</h3>
    <ul>
        {% for category in categories %}
        <a href="{% url 'auctions:category' category.id %}"><li>{{ category.category_name }}</li></a>
        {% empty %}
        <li>No category yet.</li>
        {% endfor %}
    </ul>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h3>{{ category.category_name }}</h3>
    <div class="card" style="width: 18rem;">
        <img src="{{ auction_list.image }}" class="card-img-top" alt="...">
        <div class="card-body">
        <h5 class="card-title">{{ auction_list.listing_name }}</h5>
        <a href="{% url 'auctions:listing' auction_list.id %}" class="btn btn-primary">Go to Listing</a>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends 'auctions/layout.html' %}

{% block body %}
<form action="{% url 'auctions:create_listing' %}" method="post">
    {% csrf_token %}
    <table>
        <tbody>
            <tr>
                <th><label for="id_category">Category:</label></th>
                <td>
                    <select name="category" required="" id="id_category">
                        <option value="" selected="">---------</option>
                        {% for cat_obj in cat_objs %}
                        <option value="{{ cat_obj.id }}" selected="">{{ cat_obj.category_name }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>

            <tr>
                <th><label for="id_listing_name">Listing name:</label></th>
                <td>
                    <input type="text" name="listing_name" maxlength="50" required="" id="id_listing_name">
                </td>
            </tr>

            <tr>
                <th><label for="id_image">Image:</label></th>
                <td>
                    <input type="url" name="image" maxlength="200" required="" id="id_image">
                </td>
            </tr>

            <tr>
                <th><label for="id_start_bid">Start bid:</label></th>
                <td>
                    <input type="number" name="start_bid" step="0.01" required="" id="id_start_bid">
                </td>
            </tr>

            <tr>
                <th><label for="id_description">Description:</label></th>
                <td>
                    <textarea name="description" cols="40" rows="10" required="" id="id_description"
                        spellcheck="false"></textarea>
                </td>
            </tr>
        </tbody>
    </table>
    <input type="submit">
</form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Active Listings</h2>

<div>
    {% for listing in listings %}
    <div class="card mb-3" style="width: 100%; display: flex; flex-direction: row;">
        <img style="object-fit: contain; height: 300px; width: 500px;" src="{{ listing.image }}" class="card-img-top" alt="...">
        <div class="card-body">
            <a href="{% url 'auctions:listing' listing.id %}" style="text-decoration: none; color: black;"><h5 class="card-title">{{ listing.listing_name }}</h5></a>
            <p class="card-text"><b>Price: $</b>{{ listing.start_bid }}</p>
            <p class="card-text"><em>{{ listing.description }}</em></p>
            <p class="card-text"><small class="text-muted">{{ listing.created_at }}</small></p>
        </div>
    </div>
    {% empty %}
    <div class="card">No Listings.</div>
    {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:all_categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:my_watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create_listing' %}">Create Listings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}

{% block body %}
<div>
    <style>
        h3 {
            text-decoration: underline;
            margin-top: 10px;
        }

        img {
            border: 5px solid gray;
            border-radius: 10px;
        }

        #inputs {
            border: 5px solid gray;
            border-radius: 10px;
        }

        #head {
            display: flex;
        }
    </style>
    <div>
        {% if not list_status %}
        <div class="alert alert-info" role="alert">
            {{ winner }}
        </div>
        {% endif %}
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
        {% endif %}
        <div id="head">
            <h2>Listing: {{ listing.listing_name }}</h2>
            <div style="padding: 10px;">
                {% if list_status %}
                {% if watchlist %}
                <a href="{% url 'auctions:add_to_watchlist' listing.id %}"><span
                        class="badge text-bg-secondary">Watchlist</span></a>
                {% else %}
                <a href="{% url 'auctions:add_to_watchlist' listing.id %}"><span
                        class="badge text-bg-secondary">Un-Watch</span></a>
                {% endif %}
                {% endif %}
            </div>
            {% if list_status %}
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:close_listing' listing.id %}" style="color: red;">Close this Listing</a>
                    </li>
                </ul>
            {% else %}
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:close_listing' listing.id %}" style="color: red;">Open this Listing</a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
    <img src="{{ listing.image }}">
    <h6><em>{{ listing.description }}</em></h6>
    <h3>${{ listing.start_bid }}</h3>

    {% if list_status and bid_option and listing.highest_bid %}
    <h5>The current highest bid is: ${{ listing.highest_bid.bidding }}</h5>
    {% endif %}
    
    {% if list_status and bid_option %}
    <form action="{% url 'auctions:listing' listing.id %}" method="post">
        {% csrf_token %}
        <input id="inputs" type="number" name="price" class="price-input" placeholder="Enter Bid" required>
        <input type="submit" class="btn btn-primary">
    </form>
    {% endif %}

    <h3>Details:</h3>
    <ul>
        <li>Listed By: <b>{{ listing.user.username }}</b></li>
        <li>Category: <b>{{ listing.category }}</b></li>
        <li>Created on: <b>{{ listing.created_at.date }}</b></li>
    </ul>
    
    {% if list_status %}
    <form action="{% url 'auctions:add_comment' listing.id %}" method="post">
        {% csrf_token %}
        <input id="inputs" type="text" name="comment" placeholder="Enter Comment" required>
        <input type="submit" class="btn btn-primary">
    </form>
    {% endif %}

    <h3 style="margin-top: 10px;">Comments:</h3>
    {% for comment in comments %}
    <ul>
        <li style="margin: 2px;">
            <div>
                <h5>{{ comment.user.username }}</h5>
                <p>{{ comment.comment }}</p>
            </div>
        </li>
    </ul>
    {% empty %}
    <li>No Comments Yet.</li>
    {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}

{% block body %}
    <h3>Watchlist</h3>
    <ul>
        {% for watchlist in watchlists %}
            <div class="card" style="width: 18rem;">
                <img src="{{ watchlist.image }}" class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title">{{ watchlist.listing_name }}</h5>
                <a href="{% url 'auctions:listing' watchlist.id %}" class="btn btn-primary">Go to Listing</a>
                </div>
            </div>
        {% empty %}
            <h5>Nothing in Watchlist.</h5>
        {% endfor %}
    </ul>
{% endblock %}