commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("Search_Results", views.search_bar, name="search_bar"),
    path("<name>", views.title, name="title"),
    path("Entries/New", views.New_Entry, name="new_entry"),
    path("<name>/edit", views.Edit_Entry, name="edit_entry"),
    path("Entries/Random", views.Random_Entry, name="random_entry"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from turtle import width
from attr import attrs
from django.http import HttpResponse,HttpResponseRedirect
from requests import request
from . import util
import markdown2
from django import forms
from django.shortcuts import render
from django.urls import reverse
from random import choice

def search_title(name):
    lines = util.get_entry(name)
    if lines != None:
        html = markdown2.markdown(lines)
        return (html)
    else:
        return lines


class SearchBar(forms.Form):
    query = forms.CharField(label="",widget=forms.TextInput({ "placeholder": "Search Encyclopedia"}))

class NewEntry(forms.Form):
    title = forms.CharField(label="Title")
    textarea = forms.CharField(label="Markdown Content",widget=forms.Textarea)

class EditEntry(forms.Form):
    textarea = forms.CharField(label="Markdown Content",widget=forms.Textarea)

def index(request):
        return render(request, "encyclopedia/index.html",{
            "entries": util.list_entries(),
            "form":SearchBar()
        })

def title(request, name):
    html = search_title(name)
    if html == None:
        edit_opt = False
        return render(request,"encyclopedia/entry.html",
        {
            "Edit":edit_opt,
            "name":name,
            "form":SearchBar()
        })
    else:
        edit_opt = True
        return render(request,"encyclopedia/entry.html",
        {
            "Edit":edit_opt,
            "html_code":html,
            "form":SearchBar(),
            "name":name,
        })

def search_bar(request):
    if request.method == "POST":
        form = SearchBar(request.POST)
        if form.is_valid():
            entry = form.cleaned_data.get("query")
            html = search_title(entry)
            if html == None:
                list = util.list_entries()
                list2 = []
                for item in list:
                    if entry in item:
                        list2.append(item)
                return render(request, "encyclopedia/search_results.html",{
                "entries": list2,
                "form":SearchBar()
                })
            else:
                return HttpResponseRedirect(reverse('encyclopedia:title',args=(entry,)))
    else:
        return render(request, "encyclopedia/index.html",{
            "entries": util.list_entries(),
            "form":SearchBar()
        })

def New_Entry(request):
    if request.method == "POST":
        form = NewEntry(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            markdown = form.cleaned_data.get("textarea")
            exist = util.get_entry(title)
            if exist == None:
                util.save_entry(title,markdown)
                return HttpResponseRedirect(reverse('encyclopedia:title',args=(title,)))
            else:
                return render(request,"encyclopedia/entry.html",
                {
                    "html_code":"ERROR! Page Already Exist.",
                    "form":SearchBar()
                })
    else:
        return render(request,"encyclopedia/New_Entry.html",
        {
            "new_entry":NewEntry(),
            "form":SearchBar()
        })

def Edit_Entry(request,name):
    if request.method == "POST":
        form = EditEntry(request.POST)
        if form.is_valid():
            markdown = form.cleaned_data.get("textarea")
            util.save_entry(name,markdown)
            return HttpResponseRedirect(reverse('encyclopedia:title',args=(name,)))
    else:
        return render(request,"encyclopedia/Edit_Entry.html",
        {
            "title":name,
            "edit_entry":EditEntry(initial={'textarea':util.get_entry(name)}),
            "form":SearchBar()
        })

def Random_Entry(request):
    list = util.list_entries()
    title = choice(list)
    return HttpResponseRedirect(reverse('encyclopedia:title', args=(title, )))

encyclopedia/templates/encyclopedia/Edit_Entry.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <link href="{% static 'encyclopedia/New_Entry.css' %}" rel="stylesheet">
    <h1>Edit Page</h1>
    <form action="{% url 'encyclopedia:edit_entry' name=title %}" method="post">
        {% csrf_token %}
        <b><i><label for="id_title">Title:</label></i></b>
        <input type="text" value="{{title}}" id="id_title" readonly>
        <b><i>{{ edit_entry }}</i></b>
        <input type="submit" id="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/New_Entry.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <link href="{% static 'encyclopedia/New_Entry.css' %}" rel="stylesheet">
    <h1>New Page</h1>
    <form action="{% url 'encyclopedia:new_entry' %}" method="post">
        {% csrf_token %}
        <b><i>{{ new_entry }}</i></b>
        <input type="submit" id="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {{html_code|safe}}
    {% if Edit == True %}
        <a href="{% url 'encyclopedia:edit_entry' name=name %}">Edit</a>
    {% else %}
        <b>Page Not Found</b>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{entry}}">{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search_bar' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Related Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{entry}}">{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}